### ISSUE TITLE
Clarify install directory

### ISSUE THREAD

**Issue by jimrfenner** [udacity/reactnd-contacts-server#3]
Hello! As a relative beginner, I've gotten stuck on this step a few times because of the wording on the directions for the installation of this server. After cloning the server repo, I need to cd into the new director to run the installation and start the server. This is clear to me now, but in the 'make sure we're working with the same code' checklist, the second check is to cd into the Contacts directory. Installing and starting the server fro the Contacts dir and not the contacts/reactnd-contacts-server dir errors out. Again, i'm completely aware that people with more experience than me probably have that well figured out, but I thought clarifying that language a bit might help future students - thanks!

**Comment by MorganLKestner** [comment]
I'm having a similar issue as well. I moved all the files out of the cloned folder into the rest of the app, and still getting an error to start the server.

**Comment by dalumiller** [comment]
Had same issue

**Comment by fabiofl** [comment]
This is clear now on the README. Should be closed.
